# Database Explorer
Explore the jobs_new.db database with tables, metadata, and data

In [57]:
import sqlite3
import pandas as pd
from IPython.display import display, HTML

# Database path
db_path = "../jobs_new.db"

In [58]:
# Connect to database
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Get all tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables in database:")
for table in tables:
    print(f"  - {table[0]}")

Tables in database:
  - sqlite_sequence
  - job_postings

In [59]:
# Get metadata for each table
for table_name in [table[0] for table in tables]:
    print(f"\n{'='*50}")
    print(f"Table: {table_name}")
    print(f"{'='*50}")
    
    # Get table schema
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    
    print("\nColumns:")
    for col in columns:
        print(f"  {col[1]} ({col[2]}) - NOT NULL: {col[3]} - DEFAULT: {col[4]}")
    
    # Get row count
    cursor.execute(f"SELECT COUNT(*) FROM {table_name};")
    row_count = cursor.fetchone()[0]
    print(f"\nTotal rows: {row_count}")

==================================================
Table: sqlite_sequence
==================================================

Columns:
  name () - NOT NULL: 0 - DEFAULT: None
  seq () - NOT NULL: 0 - DEFAULT: None

Total rows: 0

==================================================
Table: job_postings
==================================================

Columns:
  job_unique_id (TEXT) - NOT NULL: 0 - DEFAULT: None
  job_title (TEXT) - NOT NULL: 0 - DEFAULT: None
  company_name (TEXT) - NOT NULL: 0 - DEFAULT: None
  experience_required (TEXT) - NOT NULL: 0 - DEFAULT: None
  location (TEXT) - NOT NULL: 0 - DEFAULT: None
  published_date (TEXT) - NOT NULL: 0 - DEFAULT: None
  apply_url (TEXT) - NOT NULL: 0 - DEFAULT: None
  source (TEXT) - NOT NULL: 0 - DEFAULT: None
  raw_source_text (TEXT) - NOT NULL: 0 - DEFAULT: None
  fetched_at (TEXT) - NOT NULL: 0 - DEFAULT: None
  experience_level (TEXT) - NOT NULL: 0 - DEFAULT: None
  external_job_id (TEXT) - NOT NULL: 0 - DEFAULT: None
  job_description (TEXT) - NOT NULL: 0 - DEFAULT: None
  score (INTEGER) - NOT NULL: 0 - DEFAULT: None

Total rows: 22

In [60]:
# Display data as DataFrames for each table
for table_name in [table[0] for table in tables]:
    print(f"\n{'='*60}")
    print(f"DATA FOR TABLE: {table_name.upper()}")
    print(f"{'='*60}")
    
    # Load table into DataFrame
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    
    # Display basic info
    print(f"Shape: {df.shape} (rows, columns)")
    print(f"Columns: {list(df.columns)}")
    print("\nFirst 5 rows:")
    display(df.head())
    
    # Show data types
    print("\nData types:")
    print(df.dtypes)
    
    # Show basic statistics for numeric columns
    numeric_cols = df.select_dtypes(include=['number']).columns
    if len(numeric_cols) > 0:
        print("\nNumeric columns statistics:")
        display(df[numeric_cols].describe())

============================================================
DATA FOR TABLE: SQLITE_SEQUENCE
============================================================
Shape: (0, 2) (rows, columns)
Columns: ['name', 'seq']

First 5 rows:

Empty DataFrame
Columns: [name, seq]
Index: []

Data types:
name    object
seq     object
dtype: object

============================================================
DATA FOR TABLE: JOB_POSTINGS
============================================================
Shape: (22, 14) (rows, columns)
Columns: ['job_unique_id', 'job_title', 'company_name', 'experience_required', 'location', 'published_date', 'apply_url', 'source', 'raw_source_text', 'fetched_at', 'experience_level', 'external_job_id', 'job_description', 'score']

First 5 rows:

,job_unique_id,job_title,company_name,experience_required,location,published_date,apply_url,source,raw_source_text,fetched_at,experience_level,external_job_id,job_description,score
0,telegram_Caterpillar_Associate_Engineer_2026-0...,Associate Engineer,Caterpillar,0 - 2 (Years),"Bangalore, India",2026-05-06 13:28:16,,Telegram,Caterpillar\nPosition: Associate Engineer\nQua...,2026-05-06 14:00:35,Fresher,Associate Engineer,None,92
1,telegram_Premium_Opening__Sde_Intern_2026-05-0...,Sde Intern,Premium Opening:,,Not specified,2026-05-06 10:32:09,https://whatsapp.com/channel/0029Vb5t5DyIHphCY...,Telegram,Premium Opening:\n\nRole - SDE Intern\nBatch -...,2026-05-06 14:00:35,Fresher,Sde Intern,None,92
2,telegram_Sinope_Associate_Software_Engineer___...,Associate Software Engineer – Mobile Applications,Sinope,0-2 years,Not specified,2026-05-06 09:45:49,https://sinope.co.in/jobs/associate-software-e...,Telegram,Sinope is hiring for Associate Software Engine...,2026-05-06 14:00:35,Fresher,Associate Software Engineer – Mobile Applications,We are seeking an Associate Software Engineer ...,92
3,telegram_Icertis_Intern__Sdet_2026-05-06_extra_2,Intern -Sdet,Icertis,,Not specified,2026-05-06 09:45:49,https://iaaviz.fa.ocs.oraclecloud.com/hcmUI/Ca...,Telegram,Icertis is hiring for Intern -SDET\nExpected S...,2026-05-06 14:00:35,Fresher,Icertis,None,94
4,telegram_Enterpret_Machine_Learning_Intern_202...,Machine Learning Intern,Enterpret,,Not specified,2026-05-06 09:45:49,https://job-boards.greenhouse.io/enterpret/job...,Telegram,Enterpret is hiring for Machine Learning Inter...,2026-05-06 14:00:35,Fresher,Machine Learning Intern,Job Application for Machine Learning Intern at...,92

Data types:
job_unique_id          object
job_title              object
company_name           object
experience_required    object
location               object
published_date         object
apply_url              object
source                 object
raw_source_text        object
fetched_at             object
experience_level       object
external_job_id        object
job_description        object
score                   int64
dtype: object

Numeric columns statistics:

           score
count  22.000000
mean   84.409091
std    13.110007
min    50.000000
25%    85.000000
50%    92.000000
75%    92.000000
max    94.000000

In [61]:
# Display all data in a clean format
for table_name in [table[0] for table in tables]:
    print(f"\n{'='*80}")
    print(f"COMPLETE DATA FOR TABLE: {table_name.upper()}")
    print(f"{'='*80}")
    
    # Load table into DataFrame
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    
    # Display all rows with proper formatting
    if len(df) == 0:
        print("Table is empty")
    else:
        # Set display options to show all columns and rows
        pd.set_option('display.max_columns', None)
        pd.set_option('display.max_rows', None)
        pd.set_option('display.width', None)
        pd.set_option('display.max_colwidth', 50)
        
        display(df)
        
        # Show row and column separation
        print(f"\nRows: {df.shape[0]}, Columns: {df.shape[1]}")
        for i, col in enumerate(df.columns):
            print(f"Column {i+1}: {col}")

================================================================================
COMPLETE DATA FOR TABLE: SQLITE_SEQUENCE
================================================================================
Table is empty

================================================================================
COMPLETE DATA FOR TABLE: JOB_POSTINGS
================================================================================

,job_unique_id,job_title,company_name,experience_required,location,published_date,apply_url,source,raw_source_text,fetched_at,experience_level,external_job_id,job_description,score
0,telegram_Caterpillar_Associate_Engineer_2026-0...,Associate Engineer,Caterpillar,0 - 2 (Years),"Bangalore, India",2026-05-06 13:28:16,,Telegram,Caterpillar\nPosition: Associate Engineer\nQua...,2026-05-06 14:00:35,Fresher,Associate Engineer,None,92
1,telegram_Premium_Opening__Sde_Intern_2026-05-0...,Sde Intern,Premium Opening:,,Not specified,2026-05-06 10:32:09,https://whatsapp.com/channel/0029Vb5t5DyIHphCY...,Telegram,Premium Opening:\n\nRole - SDE Intern\nBatch -...,2026-05-06 14:00:35,Fresher,Sde Intern,None,92
2,telegram_Sinope_Associate_Software_Engineer___...,Associate Software Engineer – Mobile Applications,Sinope,0-2 years,Not specified,2026-05-06 09:45:49,https://sinope.co.in/jobs/associate-software-e...,Telegram,Sinope is hiring for Associate Software Engine...,2026-05-06 14:00:35,Fresher,Associate Software Engineer – Mobile Applications,We are seeking an Associate Software Engineer ...,92
3,telegram_Icertis_Intern__Sdet_2026-05-06_extra_2,Intern -Sdet,Icertis,,Not specified,2026-05-06 09:45:49,https://iaaviz.fa.ocs.oraclecloud.com/hcmUI/Ca...,Telegram,Icertis is hiring for Intern -SDET\nExpected S...,2026-05-06 14:00:35,Fresher,Icertis,None,94
4,telegram_Enterpret_Machine_Learning_Intern_202...,Machine Learning Intern,Enterpret,,Not specified,2026-05-06 09:45:49,https://job-boards.greenhouse.io/enterpret/job...,Telegram,Enterpret is hiring for Machine Learning Inter...,2026-05-06 14:00:35,Fresher,Machine Learning Intern,Job Application for Machine Learning Intern at...,92
5,telegram_Autodesk_Software_Development_Enginee...,Software Development Engineer,Autodesk,0 - 2 (Years),"Bengaluru, India",2026-05-06 09:45:49,https://autodesk.wd1.myworkdayjobs.com/en-US/E...,Telegram,Autodesk\nPosition: Software Development Engin...,2026-05-06 14:00:35,Fresher,Job ID 123,We are seeking a highly motivated and detail-o...,92
6,telegram_Hiring_Via_Online_Test_Not_specified_...,Not specified,Hiring Via Online Test,,Not specified,2026-05-06 09:45:49,https://tinyurl.com/AINCAT-Naukri-2026,Telegram,"Hiring via online test\nCompanies: Adani, Sony...",2026-05-06 14:00:35,Experienced,Not specified,All India Online Aptitude Test 2026 (AINCAT) |...,92
7,gmail_19dfbf91ce3958d9_0,Data Scientist,YO IT CONSULTING,Not specified,Remote,06 May 2026 06:28:19,https://in.indeed.com/jobs?q=data+scientist&hl...,Gmail,"Subject: Apply to jobs at YO IT CONSULTING, Ci...",2026-05-06 14:00:36,Experienced,Data Scientist,None,92
8,gmail_19dfbf91ce3958d9_1,Data Scientist,Ciklum,Not specified,Remote,06 May 2026 06:28:19,https://in.indeed.com/rc/clk/dl?jk=ec25858b2f0...,Gmail,"Subject: Apply to jobs at YO IT CONSULTING, Ci...",2026-05-06 14:00:36,Experienced,Data Scientist,None,92
9,gmail_19dfbf91ce3958d9_2,Data Scientist,CosmicFusion Labs,Not specified,Remote,06 May 2026 06:28:19,https://in.indeed.com/rc/clk/dl?jk=f4cf78de0fc...,Gmail,"Subject: Apply to jobs at YO IT CONSULTING, Ci...",2026-05-06 14:00:36,Experienced,Data Scientist,None,92
10,gmail_19df9c6a1ea0b284_direct,AI/ML Engineer (Associate),Bosch Group,Not specified,Not specified,05 May 2026 20:13:54,https://cts.indeed.com/v3/H4sIAAAAAAAA_42RzY6b...,Gmail,Subject: AI/ML Engineer (Associate) @ Bosch Gr...,2026-05-06 14:00:36,Experienced,AI/ML Engineer (Associate),None,92
11,gmail_19de379378cf856d_linkedin,"A Product Data Scientist, Gte Data Science And Ml",Google,Not specified,Not specified,1 May 2026 12:17:45,https://www.linkedin.com/comm/jobs/collections...,Gmail,Subject: Google is hiring a Product Data Scien...,2026-05-06 14:00:37,Experienced,"A Product Data Scientist, Gte Data Science And Ml",Sign in LinkedIn We're signing you in Discover...,92
12,telegram_20260507_094747_02,Software Engineer - Fullstack Developer,HPE,Experienced,"Bangalore, India",2026-05-07 09:47:47,https://careers.hpe.com/us/en/job/1205750/Soft...,Telegram,📌𝐇𝐏𝐄 - Software Engineer - Fullstack Developer...,2026-05-07 12:10:34,Senior-level,Software Engineer - Fullstack Developer,Software Engineer- Fullstack Developer in Beng...,50
13,telegram_20260507_094747_03,QA Software Engineer,Harmonic,"2021, 2022, 2023, 2024 grads",Bangalore,2026-05-07 09:47:47,https://egmn.fa.us2.oraclecloud.com/hcmUI/Cand...,Telegram,📌Harmonic is hiring QA Software Engineer \nFor...,2026-05-07 12:10:34,Entry-level to Mid-level,QA Software Engineer,Harmonic Inc.,62
14,telegram_20260507_094747_04,Web Solutions Engineer,Google,2024/23 passouts,Not specified,2026-05-07 09:47:47,https://www.google.com/about/careers/applicati...,Telegram,📌Company Name: Google\nRole Name: Web Solution...,2026-05-07 12:10:34,Entry-level,"Web Solutions Engineer I, Youtube Support Systems","Design, build, deploy, and improve elegant, an...",85
15,telegram_20260507_094747_05,Engineer,Qualcomm,2025-2024 passouts,Not specified,2026-05-07 09:47:47,https://careers.qualcomm.com/careers/job/44671...,Telegram,📌Company name: Qualcomm\nRole name: Engineer\n...,2026-05-07 12:10:34,Entry-level,Engineer,Careers at Qualcomm,50
16,telegram_20260506_132816_06,Associate Engineer,Caterpillar,0 - 2 (Years),"Bangalore, India",2026-05-06 13:28:16,https://careers.caterpillar.com/en/jobs/r00003...,Telegram,Caterpillar\nPosition: Associate Engineer\nQua...,2026-05-07 12:10:34,Entry-level,Associate Engineer,None,85
17,gmail_linkedin_20260507_01,Data Scientist,Kline + Company,Not specified,"Hyderabad, India",2026-05-06 12:17:55,https://www.linkedin.com/comm/jobs/view/440039...,Gmail,Kline + Company is hiring a Data Scientist (Hy...,2026-05-07 12:17:30,Mid-level,Data Scientist,None,85
18,gmail_indeed_20260507_02,AI/ML Engineer (Associate),Bosch Group,Not specified,"Coimbatore, Tamil Nadu",2026-05-05 20:13:54,https://cts.indeed.com/v3/H4sIAAAAAAAA_42RzY6b...,Gmail,AI/ML Engineer (Associate) @ Bosch Group - You...,2026-05-07 12:17:30,Entry-level,AI/ML Engineer (Associate),None,85
19,gmail_indeed_20260507_03,Data Scientist,YO IT CONSULTING,Not specified,Remote,2026-05-06 06:28:19,https://www.indeed.com/,Gmail,YO IT CONSULTING is hiring for Data Scientist ...,2026-05-07 12:17:30,Mid-level,Data Scientist,None,85
20,gmail_linkedin_20260507_04,Graduate Engineering Trainee,VCS Quality Services Pvt. Ltd.,Freshers,Not specified,2026-05-05 12:18:00,https://www.linkedin.com/comm/jobs/,Gmail,Graduate Engineering Trainee: VCS Quality Serv...,2026-05-07 12:17:30,Entry-level,Graduate Engineering Trainee,None,82
21,gmail_swissre_20260507_05,Various Positions,Swiss Re,Not specified,Not specified,2026-05-06 07:56:23,https://careers.swissre.com/,Gmail,New Swiss Re Jobs Posted - Thank you for setti...,2026-05-07 12:17:30,Various,Various Positions,Jobs and Careers at Swiss Re Jobs and Careers ...,82

Rows: 22, Columns: 14
Column 1: job_unique_id
Column 2: job_title
Column 3: company_name
Column 4: experience_required
Column 5: location
Column 6: published_date
Column 7: apply_url
Column 8: source
Column 9: raw_source_text
Column 10: fetched_at
Column 11: experience_level
Column 12: external_job_id
Column 13: job_description
Column 14: score

In [62]:
# Specific query to see job postings with chances
print("Job Postings with Chances:")
df_jobs = pd.read_sql_query("""
    SELECT job_unique_id, job_title, company_name, experience_required, location, score
    FROM job_postings 
    WHERE score IS NOT NULL
    ORDER BY score DESC
""", conn)

display(df_jobs)

print(f"\nTotal jobs with scores: {len(df_jobs)}")
print(f"Score range: {df_jobs['score'].min()} - {df_jobs['score'].max()}")

Job Postings with Chances:

,job_unique_id,job_title,company_name,experience_required,location,score
0,telegram_Icertis_Intern__Sdet_2026-05-06_extra_2,Intern -Sdet,Icertis,,Not specified,94
1,telegram_Caterpillar_Associate_Engineer_2026-0...,Associate Engineer,Caterpillar,0 - 2 (Years),"Bangalore, India",92
2,telegram_Premium_Opening__Sde_Intern_2026-05-0...,Sde Intern,Premium Opening:,,Not specified,92
3,telegram_Sinope_Associate_Software_Engineer___...,Associate Software Engineer – Mobile Applications,Sinope,0-2 years,Not specified,92
4,telegram_Enterpret_Machine_Learning_Intern_202...,Machine Learning Intern,Enterpret,,Not specified,92
5,telegram_Autodesk_Software_Development_Enginee...,Software Development Engineer,Autodesk,0 - 2 (Years),"Bengaluru, India",92
6,telegram_Hiring_Via_Online_Test_Not_specified_...,Not specified,Hiring Via Online Test,,Not specified,92
7,gmail_19dfbf91ce3958d9_0,Data Scientist,YO IT CONSULTING,Not specified,Remote,92
8,gmail_19dfbf91ce3958d9_1,Data Scientist,Ciklum,Not specified,Remote,92
9,gmail_19dfbf91ce3958d9_2,Data Scientist,CosmicFusion Labs,Not specified,Remote,92
10,gmail_19df9c6a1ea0b284_direct,AI/ML Engineer (Associate),Bosch Group,Not specified,Not specified,92
11,gmail_19de379378cf856d_linkedin,"A Product Data Scientist, Gte Data Science And Ml",Google,Not specified,Not specified,92
12,telegram_20260507_094747_04,Web Solutions Engineer,Google,2024/23 passouts,Not specified,85
13,telegram_20260506_132816_06,Associate Engineer,Caterpillar,0 - 2 (Years),"Bangalore, India",85
14,gmail_linkedin_20260507_01,Data Scientist,Kline + Company,Not specified,"Hyderabad, India",85
15,gmail_indeed_20260507_02,AI/ML Engineer (Associate),Bosch Group,Not specified,"Coimbatore, Tamil Nadu",85
16,gmail_indeed_20260507_03,Data Scientist,YO IT CONSULTING,Not specified,Remote,85
17,gmail_linkedin_20260507_04,Graduate Engineering Trainee,VCS Quality Services Pvt. Ltd.,Freshers,Not specified,82
18,gmail_swissre_20260507_05,Various Positions,Swiss Re,Not specified,Not specified,82
19,telegram_20260507_094747_03,QA Software Engineer,Harmonic,"2021, 2022, 2023, 2024 grads",Bangalore,62
20,telegram_20260507_094747_02,Software Engineer - Fullstack Developer,HPE,Experienced,"Bangalore, India",50
21,telegram_20260507_094747_05,Engineer,Qualcomm,2025-2024 passouts,Not specified,50

Total jobs with scores: 22
Score range: 50 - 94

In [63]:
# Close connection
conn.close()
print("Database connection closed.")

Database connection closed.